spring.application.name=01-openapi

# =============================================================================
# springdoc-openapi -- Configuration de Swagger UI
# =============================================================================

# URL d'acces a l'interface Swagger UI (defaut : /swagger-ui/index.html)
springdoc.swagger-ui.path=/swagger-ui.html

# URL du fichier JSON OpenAPI brut (defaut : /v3/api-docs)
springdoc.api-docs.path=/v3/api-docs

# Tri alphabetique des endpoints et des tags
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

# En production : decommentez ces lignes pour desactiver Swagger UI ou bien protégez-le par une authentification
# springdoc.swagger-ui.enabled=false
# springdoc.api-docs.enabled=false
